apiVersion: v1
kind: Secret
metadata:
  name: commentapp-secret2
type: Opaque
stringData:
  db_name: postgres
  db_password: root
  server_port: "9090"
  db-url: jdbc:postgresql://34.121.76.54:1414/commentAppDb
